package csg;

/**
 * This enum provides a list of all the user interface
 * text that needs to be loaded from the XML properties
 * file. By simply changing the XML file we could initialize
 * this application such that all UI controls are provided
 * in another language.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum csgProp {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    UNDERGRADUATE_COLUMN_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    CLEAR_BUTTON_TEXT,
    ADD_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    // THESE ARE FOR TA DETAILS TAB
    TA_DETAILS_TAB,
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    
    //THESE ARE FOR COURSE DETAILS TAB
    COURSE_DETAILS_TAB,
    COURSE_INFO_LABEL,
    SITE_TEMPLATE_LABEL,
    PAGE_STYLE_LABEL,
    SCHEDULE_DETAILS_TAB,
    SCHEDULE_BOUNDARIES_LABEL,
    SCHEUDLE_ITEMS_LABEL,
    SUBJECT_LABEL,
    NUMBER_LABEL,
    SEMESTER_LABEL,
    YEAR_LABEL,
    TITLE_LABEL,
    INSTRUCTOR_NAME_LABEL,
    INSTRUCTOR_HOME_LABEL,
    EXPORT_DIRECTORY_LABEL,
    BANNER_IMAGE_LABEL,
    LEFT_FOOTER_IMAGE_LABEL,
    RIGHT_FOOTER_IMAGE_LABEL,
    STYLE_SHEET_LABEL,
    DISCLAIMER_LABEL,
    STYLE_DISCALIMER_LABEL,
    SELECT_DIRECTORY_LABEL,
    
    RECITATION_MAIN_LABEL,
    ADD_EDIT_LABEL,
    SECTION_LABEL,
    INSTRUCTOR_LABEL,
    DAY_TIME_LABEL,
    LOCATION_LABEL,
    SUPERVISING_TA_LABEL,
    ADD_RECITATION_BUTTON,
    CLEAR_RECITATION_BUTTON,
    UPDATE_RECITATION_BUTTON,
    MISSING_SECTION_TITLE,
    MISSING_SECTION_MESSAGE,
    MISSING_INSTRUCTOR_TITLE,
    MISSING_INSTRUCTOR_MESSAGE,
    MISSING_LOCATION_TITLE,
    MISSING_LOCATION_MESSAGE,
    MISSING_DAYTIME_TITLE,
    MISSING_DAYTIME_MESSAGE,
    SECTION_NOT_UNIQUE_TITLE,
    SECTION_NOT_UNIQUE_MESSAGE,
    

    MINIMIZE_BUTTON,
    //THESE ARE FOR RECITATION DETAILS TAB
    RECITATION_DETAILS_TAB,
    
    //THESE ARE FOR SCHEDULE DETAILS TAB
    SCHEDULE_MAIN_LABEL,
    TYPE_LABEL,
    TIME_LABEL,
    DATE_LABEL,
    LINK_LABEL,
    TOPIC_LABEL,
    CRITERIA_LABEL,
    STARTDATE_LABEL,
    ENDDATE_LABEL,
    SCHEDULE_ITEMS_LABEL,
    CALENDARBOUNDARIES_LABEL,
    ADD_SCHEDULE_BUTTON,
    
    
    //THESE ARE FOR PROEJCT DETAILS TAB
    PROJECT_DETAILS_TAB,
    FIRST_NAME_LABEL,
    LAST_NAME_LABEL,
    TEAM_NAME_LABEL,
    ROLE_LABEL,
    CHANGE_BUTTON,
    SELECT_TEMPLATE_BUTTON,
    USE_LABEL,
    NAVBAR_TITLE_LABEL,
    FILE_NAME_LABEL,
    SCRIPT_LABEL,
    TA_LABEL,
    COLOR_COLUMN_TEXT,
    TEXT_COLOR_TEXT,
    
    ADD_STUDENT_BUTTON,
    MISSING_FIRST_NAME_TITLE,
    MISSING_LAST_NAME_TITLE,
    MISSING_TEAM_TITLE,
    MISSING_ROLE_TITLE,
    MISSING_FIRST_NAME_MESSAGE,
    MISSING_LAST_NAME_MESSAGE,
    MISSING_TEAM_MESSAGE,
    MISSING_ROLE_MESSAGE,
    
    
    START_TIME_LABEL,
    END_TIME_LABEL,
    SUBMIT_BUTTON_LABEL,
    
}
